### ISSUE TITLE
could you also add the jsons for the wavedrom to the repo ?

### ISSUE THREAD

**Issue by geosone** [adrienkohlbecker/65C816#1]
it would be a great starting point for other projects.

**Comment by adrienkohlbecker** [comment]
Hey! Thanks for your feedback 🙂

They are already there, you can click to expand above each image. 

Note that I'm using a fork of wavedrom as some of the functionality I need is not available upstream. I plan on contributing it when I have the time 

![image](https://user-images.githubusercontent.com/70469/156988716-fcef42ce-e903-433b-9f96-1065512c139f.png)

**Comment by geosone** [comment]
thx i did not see it.
